version: "3.9"  
services:
  Server:
    container_name: TOUR-Server
    image: maxwellmichael/disposition:TOUR-Latest
    depends_on:
      - TMysql
    working_dir: /app
    restart: always
    environment:
      - PORT=$PORT
      - SQL_PORT=$SQL_PORT
      - SQL_USR=$SQL_USR
      - SQL_PW=$SQL_PW
      - SQL_DB=$SQL_DB
      - SQL_HST=TMysql
      - KEY=$KEY
    ports:
      - $PORT:$PORT
    volumes:
      - /home/maxwell/Test/photos:/app/static/photos
  TMysql:
    container_name: TOUR-DB
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=$SQL_DB
      - MYSQL_ROOT_PASSWORD=$SQL_PW
      - MYSQL_USER=$SQL_USR
      - MYSQL_PASSWORD=$SQL_PW
      - MYSQL_TCP_PORT=$SQL_PORT
    ports:
      - $SQL_PORT:$SQL_PORT
    volumes:
      - /home/maxwell/Test/TSQL:/var/lib/mysql